name: Publish production Typescript changes (OTA update)

# 2026/01/03: disabled manually until ui-v2 release
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - run: yarn --dev --frozen-lockfile
      - run: yarn test
        working-directory: expo54

      # https://github.com/expo/expo-github-action
      # login to expo. using their action avoids ENOSPC: https://github.com/expo/expo-github-action/issues/20
      - uses: expo/expo-github-action@8.2.1
        with:
          expo-version: 6.x
          token: ${{ secrets.EXPO_TOKEN }}
      - run: npm install -g eas-cli # this one doesn't like local installs for some reason
      - run: ./expo54/scripts/eas-ota-publish # `expo publish` plus some prepublish chores, using eas-cli
